//-----------------------------
// @author: Anjani Shukla
// @date: 29 Sept 2017
// @param: TriggerParameters
// @description:  AfterInsert dispatcher event handler class that calls the functions in OpportunityMethods.
// @return: NA
//-----------------------------

public class ChangeLogJobBeforeInsertHandler  extends TriggerHandlerBase {
    //-----------------------------
    // @author: Anjani Shukla
    // @date: 29 Sept 2017
    // @param: TriggerParameters
    // @description:  Before INsert - This is used for WRF POLK
    // @return: NA
    //-----------------------------
    public override void mainEntry(TriggerParameters tp) {
    
    }
    
}