//-----------------------------
// @author Anjani Shukla
// @date 29 Sept 2017
// @param: TriggerParameters
// @description:  AfterInsert dispatcher event handler class that calls the functions in OpportunityMethods.
// @return: NA
//-----------------------------

public class ChangeLogAfterUpdateHandler extends TriggerHandlerBase {
    //-----------------------------
    // @author Anjani Shukla
    // @date 29 Sept 2017
    // @param: TriggerParameters
    // @description:  AfterUpdate - This Method is used in WRF_POLK.
    // @return: NA
    //-----------------------------
    public override void mainEntry(TriggerParameters tp) {
    
    }
}